### Slicing ile elemanlara erismek (Arraylerin alt kumesine erismek)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

1-Tek boyuttaki:

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
a[::2]

array([20, 22, 24, 26, 28])

2-Iki boyuttaki:

In [8]:
m = np.random.randint(10,size = (5,5))

In [9]:
m

array([[1, 8, 1, 0, 2],
       [7, 3, 7, 5, 1],
       [9, 6, 4, 6, 8],
       [5, 0, 0, 7, 7],
       [9, 3, 2, 8, 3]])

In [10]:
m[:,0]

array([1, 7, 9, 5, 9])

In [11]:
m[:,1]

array([8, 3, 6, 0, 3])

In [16]:
m[0,:]

array([1, 8, 1, 0, 2])

In [15]:
m[0]

array([1, 8, 1, 0, 2])

In [17]:
m[1,:]

array([7, 3, 7, 5, 1])

In [18]:
m[0:2, 0:3]

array([[1, 8, 1],
       [7, 3, 7]])

In [20]:
m[0:4, ::]

array([[1, 8, 1, 0, 2],
       [7, 3, 7, 5, 1],
       [9, 6, 4, 6, 8],
       [5, 0, 0, 7, 7]])

In [21]:
m[::, :2] 

array([[1, 8],
       [7, 3],
       [9, 6],
       [5, 0],
       [9, 3]])

In [22]:
m[:, :2]

array([[1, 8],
       [7, 3],
       [9, 6],
       [5, 0],
       [9, 3]])

In [23]:
m[:, 0:2]

array([[1, 8],
       [7, 3],
       [9, 6],
       [5, 0],
       [9, 3]])

In [24]:
m[1:3, 0:2]

array([[7, 3],
       [9, 6]])