### Alt Kume uzerinde islem yapmak 

In [2]:
import numpy as np
a = np.random.randint(10,size = (5,5))
a

array([[4, 2, 4, 5, 2],
       [2, 2, 2, 7, 9],
       [1, 7, 7, 5, 5],
       [8, 9, 4, 2, 6],
       [6, 9, 5, 5, 0]])

Bir arrayin alt kumesine eristirdikten sonra isimlendirip kaydettigimizi dusunelim. Kaydedilen bu arrayde degisiklik yaptigimizda arrayin ilk halinde de degisiklik olmaktadir. Bazi durumlarda bu degisikligin olmasini istemeyiz.Bu tip durumlarda alt kumeleri bagimszilastirmak denilen birislem yapmamiz gerekmektedir.

In [4]:
alt_a = a[0:3, 0:2]
alt_a

array([[4, 2],
       [2, 2],
       [1, 7]])

In [5]:
alt_a[0,0] = 9999
alt_a[1,1] = 888

In [6]:
alt_a

array([[9999,    2],
       [   2,  888],
       [   1,    7]])

In [7]:
a

array([[9999,    2,    4,    5,    2],
       [   2,  888,    2,    7,    9],
       [   1,    7,    7,    5,    5],
       [   8,    9,    4,    2,    6],
       [   6,    9,    5,    5,    0]])

alt_a'da yapilan bir degisiklik hem alt_a'da hem de a'da meydana geldi.

Bunu engellemek icin copy isimli bir metod kullaniriz.

In [8]:
m = np.random.randint(10,size = (5,5))
m

array([[6, 3, 7, 8, 6],
       [5, 9, 4, 8, 0],
       [6, 8, 0, 7, 2],
       [7, 7, 6, 1, 8],
       [9, 2, 1, 1, 3]])

In [9]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[6, 3],
       [5, 9],
       [6, 8]])

In [11]:
alt_b[0,0] = 9999
alt_b

array([[9999,    3],
       [   5,    9],
       [   6,    8]])

In [12]:
m

array([[6, 3, 7, 8, 6],
       [5, 9, 4, 8, 0],
       [6, 8, 0, 7, 2],
       [7, 7, 6, 1, 8],
       [9, 2, 1, 1, 3]])

oLusturulan ilk arrayin yapisinda bir degisiklik meydana gelmemis oldu.