### Fancy index ile elemanlara erismek

In [1]:
import numpy as np
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Fancy kelime anlami itibariyle fantastik, buyuleyici gibi anlamlara gelmektedir. Bize hem ileride gorecek oldugumuz pandas dataframe'lerinde hem de numpy arraylerinde daha ileri duzey eleman secme imkanlari vermektedir. Daha ileri duzeyde eleman secmemize olanak saglayacak.

In [2]:
v[1]

3

In [ ]:
v[3]

9

In [4]:
v[5]

15

In [5]:
[v[1], v[3], v[5]]

[3, 9, 15]

Tek Boyutta Fancy Index:

In [6]:
al_getir = [1,3,5]

In [7]:
v[al_getir]

array([ 3,  9, 15])

Iki Boyutta Fancy Index:

In [8]:
m = np.arange(9).reshape((3,3))

In [9]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [11]:
m[satir,sutun]

array([1, 5])

Basit index ile fancy index

In [12]:
m[0, [1,2]]

array([1, 2])

Slice ile fancy:

In [13]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])