### Matematiksel Islemler:

In [2]:
import numpy as np
v = np.array([1,2,3,4,5])

In [3]:
v - 1

array([0, 1, 2, 3, 4])

In [4]:
v * 5

array([ 5, 10, 15, 20, 25])

In [5]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
v*5/10--1

array([1.5, 2. , 2.5, 3. , 3.5])

## ufunc:

In [7]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [8]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [9]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [10]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [11]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [12]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.absolute([np.array([-3])])

array([[3]])

In [14]:
np.sin(360)

0.9589157234143065

In [15]:
np.cos(180)

-0.5984600690578581

In [16]:
v = np.array([1,2,3])

In [17]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [19]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [20]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [21]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\aleyy\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\aleyy\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

## cheatsheet:

numpy mathematics cheatshits -> you can google it.