### Alıştırmalar

In [2]:
import numpy as np

1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturalım.

In [3]:
result = np.array([10,15,30,45,60])
print(result)

[10 15 30 45 60]


2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

In [4]:
result = np.arange(5,15)
print(result)

[ 5  6  7  8  9 10 11 12 13 14]


3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

In [5]:
result = np.arange(50,100,5)
print(result)

[50 55 60 65 70 75 80 85 90 95]


4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

In [6]:
result = np.zeros(10)
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

In [7]:
result = np.ones(10)
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


6- (0-100) arasında eşit aralıklı 5 sayı üretin.

In [8]:
result = np.linspace(0,100,5)
print(result)

[  0.  25.  50.  75. 100.]


7- (10-30) arasında rastgele 5 tane tamsayı üretin.

In [9]:
result = np.random.randint(10,30,5)
print(result)

[10 14 27 22 13]


8- [-1 ile 1] arasında 10 adet sayı üretin.

In [10]:
result = np.random.rand(10)
print(result)

[8.37625275e-01 8.99374685e-01 7.87689942e-04 8.29367251e-01
 9.78526573e-01 4.61624852e-01 4.16986774e-01 4.34453807e-02
 3.60245118e-02 5.57083860e-01]


In [11]:
result = np.random.randn(10)
print(result)

[ 1.02131874  0.89599084  0.22241062 -0.73945671 -1.35884972 -0.27373952
  0.1310691   1.55071659 -0.95422824 -0.07144983]


9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

In [12]:
result = np.random.randint(10,50,15)
print(result)

[15 13 13 25 27 30 49 35 20 29 12 46 36 13 32]


In [13]:
result = np.random.randint(10,50,15).reshape(3,5)
print(result)

[[43 39 32 16 14]
 [29 20 16 45 31]
 [27 23 21 18 28]]


10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız.

In [15]:
matris = np.random.randint(10,50,15).reshape(3,5)
rowTotal = matris.sum(axis = 1)
colTotal = matris.sum(axis = 0)
print(matris)
print(rowTotal)
print(colTotal)

[[39 31 28 40 23]
 [39 37 26 29 11]
 [22 22 47 19 30]]
[161 142 140]
[100  90 101  88  64]


11- Üretilen matrisin en büyük, en küçük elemanı ve ortalaması nedir?

In [17]:
result = matris.max()
print(result)
result = matris.min()
print(result)
result = matris.mean()
print(result)

47
11
29.533333333333335


12- Üretilen matrisin en büyük değerinin indeksi kaçtır?

In [19]:
result = matris.argmax()
print(result)
result = matris.argmin()
print(result)

12
9


13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

In [20]:
arr = np.arange(10,20)
print(arr)
result = arr[:3]
print(result)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12]


14- Üretilen dizinin elemanlarını tersten yazdırın.

In [21]:
result = arr[::-1]
print(result)

[19 18 17 16 15 14 13 12 11 10]


15- Üretilen matrisin ilk satırını seçiniz.

In [22]:
result = matris[0]
print(result)

[39 31 28 40 23]


16- Üretilen matrisin 2.satır ve 3.sütunundaki elemanı hangisidir?

In [23]:
result = matris[1,2]
print(result)

26


17- Üretilen matrisin tüm satırlardaki ilk elemanını seçiniz.

In [24]:
result = matris[:,0]
print(result)

[39 39 22]


18- Üretilen matrisin her bir elemanının karesini alınız.

In [25]:
result = matris ** 2
print(result)

[[1521  961  784 1600  529]
 [1521 1369  676  841  121]
 [ 484  484 2209  361  900]]


19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır? Aralığı (-50,+50) arasında yapınız.

In [26]:
result = matris % 2 == 0
print(result)
result = matris[matris % 2 == 0]
print(result)
ciftler = matris[matris % 2 == 0]
result = ciftler > 0
print(result)
result = ciftler[ciftler > 0]
print(result)

[[False False  True  True False]
 [False False  True False False]
 [ True  True False False  True]]
[28 40 26 22 22 30]
[ True  True  True  True  True  True]
[28 40 26 22 22 30]
