### NUMPY ARRAY'I OLUSTURMAK

In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

Sabit tip baskisinin sonucu:

In [6]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

Peki bunu ayarlayamaz miyiz?

In [8]:
np.array([3.14,4,2,13],dtype = "float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [9]:
np.array([3.14,4,2,13],dtype = "int")

array([ 3,  4,  2, 13])

Sifirdan array olusturma islemleri:

Tek boyutlu(vektor) bir arraydir:

In [12]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Matematiksel anlamda matris, iki boyutlu array:

In [16]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

Dogrusal dizi olsuturma:

In [21]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [22]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Ortalaması=10 standart sapması=4 olan 3 e 4 lük bir array olusturabiliriz:

In [23]:
np.random.normal(10,4,(3,4))

array([[11.53566247, 12.61851191,  7.53509467, 15.24376866],
       [ 9.51351498,  4.28106778,  3.6659734 , 10.41545476],
       [13.28437456, 15.52782286,  8.09803966,  8.97485107]])

In [24]:
np.random.randint(0,10,(3,3))

array([[7, 0, 5],
       [1, 2, 8],
       [3, 7, 5]])