### Yeniden sekillendirme (reshaping)

In [2]:
import numpy as np

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Elimizde 1'den 10'a kadar olan sayilardan olusan bir array oldugunu dusunelim. Amacimizin bu arrayin uzerinden 3x3'luk array olusturmak oldugunu dusunelim:

In [4]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a =np.arange(1,10)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a.ndim

1

Elimizdeki tek boyutlu arrayi(vektoru) iki boyutlu arraye(matrise) donusturmek istiyoruz ama o tek boyuttaki bilgisi de oldugu sekliyle kalsin.

In [8]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

6 ve 8 hucrelerindeki arraylerin tek farki birisi tek koseli parantez icerisinde birisi ise iki koseli parantez icerisinde yer almaktadir.

In [9]:
b = a.reshape((1,9))

In [10]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
b.ndim

2

boyut bilgisini bize 2 verir cunku artik bir matristir.