### Array siralama (sorting)

1-Tek boyutlu:

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

Hucre 6'daki sort() metodu olumcul yan etkili metodlardan oldugundan dolayi arrayimizin yapisini komple degistirdi. Hucre 4'deki ise arrayin yapisini bozmadi cunku olsuturulan numpy uzerinden siralamayi gerceklestirdik.

2-Iki boyutlu:

In [9]:
np.random.normal(20,5,(3,3))

array([[19.3082249 , 11.72381534, 20.47154031],
       [22.35190164, 28.44154644, 20.92854005],
       [16.92413074, 17.00459534, 22.62825306]])

In [10]:
m = np.random.normal(20,5,(3,3))

In [11]:
m

array([[20.83568021, 20.52191404, 22.88026355],
       [22.5357136 , 27.00863431, 22.29390449],
       [20.76306361, 23.07854603, 21.79327644]])

Satir siralama:

In [12]:
np.sort(m,axis = 1)

array([[20.52191404, 20.83568021, 22.88026355],
       [22.29390449, 22.5357136 , 27.00863431],
       [20.76306361, 21.79327644, 23.07854603]])

In [13]:
np.sort(m,axis = 0)

array([[20.76306361, 20.52191404, 21.79327644],
       [20.83568021, 23.07854603, 22.29390449],
       [22.5357136 , 27.00863431, 22.88026355]])