### Index ile elemanlara ersimek

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([6, 1, 4, 7, 0, 7, 4, 8, 0, 5])

In [2]:
a[0]

6

In [3]:
a[-1]

5

In [4]:
a[0] = 100

In [5]:
a

array([100,   1,   4,   7,   0,   7,   4,   8,   0,   5])

In [6]:
m = np.random.randint(10, size = 10)
m

array([8, 6, 7, 6, 0, 1, 5, 4, 6, 4])

In [7]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 4, 4, 6, 6],
       [1, 6, 7, 0, 5],
       [9, 3, 1, 4, 8]])

In [8]:
m[0,0]

6

In [11]:
m[1,1]

6

In [16]:
m[2,4] = 88

In [17]:
m

array([[ 6,  4,  4,  6,  6],
       [ 1,  6,  7,  0,  5],
       [ 9,  3,  1,  4, 88]])

Numpy arrayleri icin fixed type yani sabitlenmis tipli demistik. Mesela burada surekli bir degeri (ornegin float tipindeki bir degisken) bu arraye eklemeye calisalim:

In [19]:
m[1,4] = 2.2

In [20]:
m

array([[ 6,  4,  4,  6,  6],
       [ 1,  6,  7,  0,  2],
       [ 9,  3,  1,  4, 88]])

Ondalik kismi atarak 2.2 degeri arraye eklendi. Onceki kisimlarda gordugumuz gibi array olusturulurken icerisinde 1 tane bile ondalikli sayi iceriyorsa diger sayilarda ondalikli sayi seklinde yazilirdi. Ancak ondalikli sayiyi sonradan eklersek eklenen sayinin ondalikli kismi alinmaz bir integer gibi arraye eklenir.  