### Array birlestirme (concatenation)

In [1]:
import numpy as np

Tek boyut uzerinde birlestirme:

In [2]:
x = np.array([1,2,3,])
y = np.array([4,5,6])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
z = np.array([7,8,9])

In [6]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Iki boyut uzerinde birlestirme:

In [8]:
a = np.array([[1,2,3],
              [4,5,6]])

In [9]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Peki satir bazinda degil de sutun bazinda birlestirmek istersek:

In [10]:
np.concatenate([a,a],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])